### ISSUE TITLE
Swift can't support

### ISSUE THREAD

**Issue by codwam** [Yalantis/YALField#3]

**Comment by Kalianey** [comment]
Same here, when I import it in the bridging header I get the error: 'Cannot find interface declaration for 'YALBaseErrorsProvider'' and 'Could not build module 'YALField'' ...

**Comment by houze2311** [comment]
Hello, Kalianey.
Thank you for your interest to our component.
You will need to use a bridging header to use them.

**Comment by codwam** [comment]
add the bridging header also error..
