### ISSUE TITLE
converte Swift

### ISSUE THREAD

**Issue by J-Arji** [Yalantis/YALField#6]
hi 
can you convert YALField to swift ?

**Comment by serejahh** [comment]
Hi @J-Arji. Thanks for your interest! 

Do you have any problems or restrictions with objective-c version?

**Comment by J-Arji** [comment]
@serejahh 
I'm not familiar with objective-c  and do not know how he did it

**Comment by serejahh** [comment]
I'm asking because you can use any objective-c lib in your swift project

**Comment by serejahh** [comment]
If you have any problems, just let me know and describe what's going wrong
